### ISSUE TITLE
Fix / PICA method to get holding records

### ISSUE THREAD

**Issue by nichtich** [gbv/Catmandu-PICA#20]
Holding records in PICA are aggregated by level 1 fields. There should be a `pica_holdings` method, similar to https://metacpan.org/pod/PICA::Record#holdings-iln.

Depends on https://github.com/gbv/PICA-Data/issues/1

**Comment by nichtich** [comment]
Could also be implemented as bind:

~~~
do pica_each_local()
   # process local record with its item records
end
~~~

~~~
do pica_each_item()
   # process all item record
end
~~~

**Comment by UschiKlute** [comment]
As in Catmandu an "item" means something like data record (Datensatz) I would prefer the PICA terminology:  pica_each_copy

**Comment by nichtich** [comment]
Could also be extension of `pica_each`, e.g. `pica_each('copy')`

**Comment by nichtich** [comment]
Implemented on the importer with option 'level' (version 1.13).
