### ISSUE TITLE
fixes pica_set and pica_add to create PICA

### ISSUE THREAD

**Issue by nichtich** [gbv/Catmandu-PICA#24]
```
# Copy from field dc.identifier to pica field 003@ subfield 0, replace first existing field
pica_set('dc.identifier','003A0');

# Copy from field dc.identifier to pica field 010@ in an additional new subfield 0
pica_add('dc.language','010@a');
```

**Comment by cKlee** [comment]
What if I want to set the string `'dc.language'` to `003A0` instead of the value of path `dc.language`? How to differ scalars and paths? Can this be achieved through an option like:

    # {"dc": {"identifier": 1234}}
    # use a path
    pica_set('dc.identifier','003A0', path:1); # ['003A', undef, '0' =>1234]
    # set a scalar
    pica_set('dc.identifier','003A0'); # ['003A', undef, '0' => 'dc.identifier']


@nichtich @jorol

**Comment by cKlee** [comment]
For `pica_set`, should all repetitions of a subfield been set?

For `pica_add`, should more than one subfield be allowed in pica path?

**Comment by cKlee** [comment]
See https://github.com/gbv/Catmandu-PICA/pull/40
