### ISSUE TITLE
Customize PICA::Writer::Plus format

### ISSUE THREAD

**Issue by nichtich** [gbv/Catmandu-PICA#4]
Some use \N{LINE FEED} and some use \N{INFORMATION SEPARATOR THREE} as record separator, so this should be configurable.

**Comment by nichtich** [comment]
PICA::Data 0.28 add "binary" PICA with INFORMATION SEPARATOR THREE as record separator. I checked all examples from https://metacpan.org/source/VOJ/PICA-Record-0.584/t/files and could parse with the existing dialects (XML, plain, plus, binary) all but: `dumpformat`, `winibwsave.example`, `winibwsave.example2` and `winibwsave.example3`. Let's keep this issue open unless these formats have dealed with.

**Comment by jorol** [comment]
Added PICA::Writer::Generic for custom field, subfield and record separators. 

ToDo:

- [ ] PICA::Parser::WinIBW

- [ ] PICA::Writer::WinIBW

**Comment by cKlee** [comment]
PICA::Writer::WinIBW ?? What should this be good for?

**Comment by jorol** [comment]
Good question;-) I delete this until someone has a use case for this.

**Comment by nichtich** [comment]
@cKlee @jorol can I close this issue? PICA::Data supports all variants listed at <http://format.gbv.de/pica> (only PICA JSON could be added to simplify access to the short form without `record =>` wrapping element if this siplifies anyones use cases)
