### ISSUE TITLE
Add support for normalized PICA+ format

### ISSUE THREAD

**Issue by Phu2** [gbv/Catmandu-PICA#47]
The GBV provides data in a "normalized" variant of the PICA+ plain format, have a look at the documentation https://verbundwiki.gbv.de/pages/viewpage.action?pageId=40009828 and the attached file [test.txt](https://github.com/gbv/Catmandu-PICA/files/1095242/test.txt)

It would be nice to do a conversion without any replacing of characters upfront, eg. by 

catmandu convert PICA --type normalized to PICA --type xml < test.txt

**Comment by cKlee** [comment]
@Phu2 Can you issue that within https://github.com/gbv/PICA-Data and close this one?

**Comment by cKlee** [comment]
@Phu2 Seems like this is already covered by PICA --type binary.

    catmandu convert PICA --type binary to PICA --type xml < test.txt

seems to work properly.

**Comment by Phu2** [comment]
Yeah, it works :) Thanks a lot, @cKlee !

**Comment by powerriegel** [comment]
Why do you add **two** \x1D at the end of each record? That won't work with our CBS. We have to remove the duplicate occurrence.

**Comment by jorol** [comment]
Could you please give an example of your conversion command and data as I couldn't reproduce the problem? I would also recommend to open an new issue.
