### ISSUE TITLE
closing tag is missing in result of conversion

### ISSUE THREAD

**Issue by Phu2** [gbv/Catmandu-PICA#49]
Seems like the closing tag `</collection>` is missing after conversion.

Example file: 
[test.txt](https://github.com/gbv/Catmandu-PICA/files/1216029/test.txt)

`catmandu convert PICA --type binary to PICA --type xml < test.txt > result.txt`

Result: 
[result.txt](https://github.com/gbv/Catmandu-PICA/files/1216030/result.txt)

**Comment by cKlee** [comment]
This is already solved in Catmandu::PICA 0.23. Please update.

**Comment by Phu2** [comment]
Ok, Thanks!
