### ISSUE TITLE
Fields with a 3-digit occurrence are skipped

### ISSUE THREAD

**Issue by Phu2** [gbv/Catmandu-PICA#51]
Example file consist of one record in plain pica format: 
[chunk.txt](https://github.com/gbv/Catmandu-PICA/files/1461512/chunk.txt)

Running 
`catmandu convert -v PICA --type binary to PICA --type XML < chunk.txt > chunk.txt.xml`

results in

`WARNING: no valid PICA field structure "203@/100 09011385967
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "206W/100 014784343Xz41409 A
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "208@/100 a27-01-09bbn
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "209A/100 b8112f1409a1409/L040/k�rschnerdix00
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "209B/100 aCC0x78
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "231@/100 d21j2007
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "231B/100 a21.2007
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "203@/101 09011386169
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "206W/101 0147843677z40324 A
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "208@/101 a27-01-09bbn
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "209A/101 b8112f0324a0324/Zi 108 Sch K�r(13)dix00
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "209B/101 aCC0x78
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "231@/101 d13j1980
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "231B/101 a13.1980,1-3
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "203@/102 0119169531X
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "206W/102 0190064153z40312 A
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "208@/102 a14-10-10bbn
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "209A/102 b8112f0312a0312/Aa 28dix00
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "209B/102 aCC0x78
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "231@/102 d10j19660d11j1970
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
WARNING: no valid PICA field structure "231B/102 a10.1966; 11.1970
". Skipped field at /usr/local/share/perl/5.22.1/Catmandu/Importer/PICA.pm line 46.
converted 1 object
done
`

**Comment by jorol** [comment]
Thanks for the bug report. I will add support for 3-digit occurrences.

**Comment by jorol** [comment]
Fixed in https://github.com/gbv/PICA-Data/releases/tag/0.34

Install new version:

```terminal
$ cpanm PICA::Data
```
