### ISSUE TITLE
Replacement of angle brackets

### ISSUE THREAD

**Issue by Phu2** [gbv/Catmandu-PICA#53]
When converting from plain pica to pica xml, Catmandu replaces `<` with `&amp;lt;`; i think it should be `&lt;` instead.

Example file (one record in plain pica format)
[angle-bracket.txt](https://github.com/gbv/Catmandu-PICA/files/1471640/angle-bracket.txt)

Command
`catmandu convert PICA --type binary to PICA --type XML < angle-bracket.txt > angle-bracket.xml` 

The resulting xml is not valid according to xmllint, see field 021A subfield a.
`xmllint angle-bracket.xml`

**Comment by jorol** [comment]
Fixed in https://github.com/gbv/PICA-Data/releases/tag/0.34

Install new version:

```terminal
$ cpanm PICA::Data
```
