### ISSUE TITLE
Fix failing GitHub actions.

### ISSUE THREAD

**Issue by nichtich** [gbv/Catmandu-PICA#74]
See https://github.com/gbv/Catmandu-PICA/runs/4364199276 - likely requires to fix https://github.com/LibreCat/Catmandu/issues/385.

**Comment by jorol** [comment]
The problem is https://github.com/perl4lib/marc-perl/issues/14. I've already created a PR https://github.com/perl4lib/marc-perl/pull/13, but still not merged...
