### ISSUE TITLE
Is it possible to add an importer for PICA --type import?

### ISSUE THREAD

**Issue by martinasiebert** [gbv/Catmandu-PICA#88]
I am missing an importer for PICA --type import. As there is an exporter (https://metacpan.org/pod/Catmandu::Exporter::PICA) would it be possible/logical to also add an importer for this format?
Aim: I have PICA data of the type import and want to add a standard field to each record, i.e. import and export PICA import.

**Comment by nichtich** [comment]
I'm working on this right now, see https://github.com/gbv/PICA-Data/issues/129

**Comment by martinasiebert** [comment]
Oh. Thanks. Sorry for not seeing this!
Great ☺
martina

Von: Jakob Voß ***@***.***>
Gesendet: Mittwoch, 9. August 2023 15:29
An: gbv/Catmandu-PICA ***@***.***>
Cc: Siebert, Dr. Martina ***@***.***>; Author ***@***.***>
Betreff: Re: [gbv/Catmandu-PICA] Is it possible to add an importer for PICA --type import? (Issue #88)


I'm working on this right now, see gbv/PICA-Data#129<https://github.com/gbv/PICA-Data/issues/129>
